# Generated by Django 4.2.6 on 2023-12-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='John Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='JohnDoe123', max_length=30, unique=True),
        ),
    ]
